name: .NET Build 
on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      PathToProject:
        description: 'Path where project is found'     
        required: true
        default: 'TailwindTraders.Website/Source/Tailwind.Traders.Web'
        
      BuildConfiguration:
        description: 'Build configuration'     
        required: true
        default: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Use Node 10.16.3
      uses: actions/setup-node@v2
      with:
        node-version: 10.16.3
    - run: npm install
      working-directory:  ${{ inputs.PathToProject }}/ClientApp        
    - name: Restore dependencies
      run: dotnet restore  ${{ inputs.PathToProject }}/Tailwind.Traders.Web.csproj
    - name: Build
      run: dotnet build  ${{ inputs.PathToProject }}/Tailwind.Traders.Web.csproj --configuration Release
    - name: Test
      run: dotnet test  ${{ inputs.PathToProject }}/Tailwind.Traders.Web.csproj --configuration Release
    - name: Publish
      run: dotnet publish  ${{ inputs.PathToProject }}/Tailwind.Traders.Web.csproj --configuration Release --output ${{ runner.temp }}/Tailwind
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: publish
        path: ${{ runner.temp }}/Tailwind